# This docker-compose file is intended for local development purposes only.

version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - '3000:3000'
    environment:
      PGRST_DB_URI: postgresql://postgres:password@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMAS: starkflare_api
      PGRST_DB_ANON_ROLE: starkflare_web_anon
    depends_on:
      - migrations
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      API_URL: http://localhost:3000/
  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations/ -database postgresql://postgres:password@db:5432/postgres?sslmode=disable up
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
